replicaCount: 1

kubeserial:
  devices: []

certManagerIssuer:
  name:
  kind: Issuer

webhook:
  image:
    repository: janekbaraniewski/kubeserial-injector-webhook
    pullPolicy: IfNotPresent
    tag: "0.1.8"

image:
  repository: janekbaraniewski/kubeserial
  pullPolicy: IfNotPresent
  tag: "0.1.8"

monitoring:
  prometheusMonitors:
    enabled: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
